export const images = {
  logo: "/assets/mx-logo-1.png",
  circle1: "/assets/bigCircle.png",
  circle2: "/assets/cylinder.png",
  circle3: "/assets/Ellipse1.png",
  circle4: "/assets/Ellipse2.png",
  circle5: "/assets/Ellipse3.png",
  circle6: "/assets/Seetings.png",
  frame1: "/assets/Frame51.png",
  section: "/assets/Section.png",
  carrer: "/assets/c1.png",
  logos: "/assets/logo.svg",
  image1: "/assets/image.avif",
  image2: "/assets/image.png",
  image3: "/assets/image2.avif",
  image4: "/assets/image3.avif",
  image5: "/assets/image4.avif",
  c1: "/assets/c12-removebg-preview.png",
  c2: "/assets/c4-removebg-preview.png",
  c3: "/assets/c5-removebg-preview.png",
  c4: "/assets/c6-removebg-preview.png",
  c5: "/assets/c8-removebg-preview.png",
  c6: "/assets/c9-removebg-preview.png",
  react: "/assets/r1.png",
  next: "/assets/n1.png",
  node: "/assets/n2.png",
  mongo: "/assets/m1.png",
  andriod: "/assets/a1.jpg",
  workImage: "/assets/workimage.png",
  whitelogo:"/assets/whitelogo.png"
};
